# Generated by Django 2.1.5 on 2019-02-06 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dating_forms', '0002_datingform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datingform',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 6, 22, 17, 50, 786995, tzinfo=utc)),
        ),
    ]
