# Generated by Django 2.1.5 on 2019-02-07 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_forms', '0003_auto_20190207_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datingform',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 20, 21, 5, 324444)),
        ),
    ]
