# Generated by Django 2.1.5 on 2019-02-12 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_forms', '0004_auto_20190207_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datingform',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 12, 14, 35, 59, 552592)),
        ),
    ]
